import { Route, TicketType, Driver } from './types';

export const ROUTES: Route[] = [
  {
    id: '219',
    number: '219',
    name: '219 (Pouze v prac. dny)',
    stops: [
      { id: '219_1', name: 'Horní Slavkov Sídliště', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '219_2', name: 'Horní Slavkov náměstí', zone: 1, kmFromStart: 1.5, minutesFromStart: 4 },
      { id: '219_3', name: 'Horní Slavkov u Nádražní školy', zone: 1, kmFromStart: 3.0, minutesFromStart: 8 },
      { id: '219_4', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 4.5, minutesFromStart: 14, arrivalMinutesFromStart: 12 },
      { id: '219_5', name: 'Horní Slavkov u kostela', zone: 1, kmFromStart: 5.5, minutesFromStart: 16 },
      { id: '219_6', name: 'Horní Slavkov Točná v Kostelní ulici', zone: 1, kmFromStart: 6.5, minutesFromStart: 18 },
      { id: '219_7', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 7.5, minutesFromStart: 20 },
      { id: '219_8', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 9.0, minutesFromStart: 25 },
      { id: '219_9', name: 'Horní Slavkov Kounice (konečná)', zone: 2, kmFromStart: 10.5, minutesFromStart: 30 },
    ],
  },
  {
    id: '120A_REG',
    number: '120/A',
    name: '120/A (Pouze v prac. dny)',
    stops: [
      { id: '120a_reg_1', name: 'Horní Slavkov staré nám.', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120a_reg_2', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 1.5, minutesFromStart: 3 },
      { id: '120a_reg_3', name: 'Horní Slavkov v zatáčce', zone: 1, kmFromStart: 2.5, minutesFromStart: 5, isOnDemand: true },
      { id: '120a_reg_4', name: 'Horní Slavkov Točná u fary', zone: 2, kmFromStart: 3.5, minutesFromStart: 7 },
      { id: '120a_reg_5', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120a_reg_6', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '120a_reg_7', name: 'Horní Slavkov Kounice', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
    ],
  },
  {
    id: '120B_REG',
    number: '120/B',
    name: '120/B (Pouze v prac. dny)',
    stops: [
      { id: '120b_reg_1', name: 'Horní Slavkov staré nám.', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120b_reg_2', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120b_reg_3', name: 'Horní Slavkov Točná v Kostelní ul.', zone: 1, kmFromStart: 2.5, minutesFromStart: 5 },
      { id: '120b_reg_4', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 4.0, minutesFromStart: 8 },
      { id: '120b_reg_5', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 5.5, minutesFromStart: 11 },
      { id: '120b_reg_6', name: 'Horní Slavkov Kounice', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
    ],
  },
  {
    id: '120C1_REG',
    number: '120/C1',
    name: '120/C1 (Pouze v prac. dny)',
    stops: [
      { id: '120c1_1', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120c1_2', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120c1_3', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 2.0, minutesFromStart: 4 },
      { id: '120c1_4', name: 'Horní Slavkov Točná ve Faře', zone: 2, kmFromStart: 3.0, minutesFromStart: 6 },
      { id: '120c1_5', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120c1_6', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 6.0, minutesFromStart: 14, arrivalMinutesFromStart: 12 },
      { id: '120c1_7', name: 'Horní Slavkov Nádražní škola', zone: 1, kmFromStart: 7.5, minutesFromStart: 16 },
      { id: '120c1_8', name: 'Horní Slavkov u šk. hřiště', zone: 1, kmFromStart: 9.0, minutesFromStart: 19, isOnDemand: true },
      { id: '120c1_9', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 11.0, minutesFromStart: 23 },
      { id: '120c1_10', name: 'Horní Slavkov náměstí', zone: 1, kmFromStart: 12.0, minutesFromStart: 25 },
      { id: '120c1_11', name: 'Horní Slavkov sídliště', zone: 1, kmFromStart: 15.0, minutesFromStart: 30 },
    ],
  },
  {
    id: '120C2_REG',
    number: '120/C2',
    name: '120/C2 (Pouze v prac. dny)',
    stops: [
      { id: '120c2_1', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120c2_2', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120c2_3', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 2.0, minutesFromStart: 4 },
      { id: '120c2_4', name: 'Horní Slavkov Točná ve Faře', zone: 2, kmFromStart: 3.0, minutesFromStart: 6 },
      { id: '120c2_5', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120c2_6', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 6.0, minutesFromStart: 14, arrivalMinutesFromStart: 12 },
      { id: '120c2_7', name: 'Horní Slavkov Náměstí', zone: 1, kmFromStart: 9.0, minutesFromStart: 19 },
      { id: '120c2_8', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 10.0, minutesFromStart: 21 },
      { id: '120c2_9', name: 'Horní Slavkov Lesopark', zone: 1, kmFromStart: 12.5, minutesFromStart: 26 },
    ],
  },
  {
    id: '120_HALDA_WD',
    number: '120/Halda',
    name: '120/Halda (Pracovní dny)',
    stops: [
      { id: '120_hwd_1', name: 'Horní Slavkov Sídliště', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120_hwd_2', name: 'Horní Slavkov halda u mostu', zone: 2, kmFromStart: 2.5, minutesFromStart: 5 },
      { id: '120_hwd_3', name: 'Horní Slavkov halda na mostě', zone: 2, kmFromStart: 3.5, minutesFromStart: 7 },
      { id: '120_hwd_4', name: 'Horní Slavkov na haldě', zone: 2, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120_hwd_5', name: 'Horní Slavkov Kounice hřiště', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
      { id: '120_hwd_6', name: 'Horní Slavkov Kounice (konečná)', zone: 2, kmFromStart: 9.0, minutesFromStart: 20 },
    ],
  },
  {
    id: '120_HALDA_WE',
    number: '120/Halda',
    name: '120/Halda (Víkendy - náhradní trasa)',
    stops: [
      { id: '120_hwe_1', name: 'Horní Slavkov sídliště', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120_hwe_2', name: 'Horní Slavkov náměstí', zone: 1, kmFromStart: 1.5, minutesFromStart: 7 },
      { id: '120_hwe_3', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 2.2, minutesFromStart: 10 },
      { id: '120_hwe_4', name: 'HS u Garáží (nad škol. hřištěm)', zone: 1, kmFromStart: 2.8, minutesFromStart: 13 },
      { id: '120_hwe_5', name: 'Horní Slavkov na mostě', zone: 1, kmFromStart: 3.5, minutesFromStart: 16 },
      { id: '120_hwe_6', name: 'Horní Slavkov u nádraží', zone: 1, kmFromStart: 4.0, minutesFromStart: 18 },
      { id: '120_hwe_7', name: 'Horní Slavkov u mostu', zone: 1, kmFromStart: 4.4, minutesFromStart: 20 },
      { id: '120_hwe_8', name: 'Horní Slavkov Halda pod mostem', zone: 1, kmFromStart: 5.1, minutesFromStart: 23 },
      { id: '120_hwe_9', name: 'Horní Slavkov Halda u mostu', zone: 2, kmFromStart: 5.6, minutesFromStart: 25 },
      { id: '120_hwe_10', name: 'Horní Slavkov Halda za mostem', zone: 2, kmFromStart: 6.7, minutesFromStart: 30 },
      { id: '120_hwe_11', name: 'Horní Slavkov na Haldě', zone: 2, kmFromStart: 7.8, minutesFromStart: 35 },
      { id: '120_hwe_12', name: 'HS Kounice u hřiště', zone: 2, kmFromStart: 8.9, minutesFromStart: 40 },
      { id: '120_hwe_13', name: 'Horní Slavkov Kounice Kounice', zone: 2, kmFromStart: 10.0, minutesFromStart: 45 },
    ],
  },
  {
    id: '120_ABX',
    number: '120/ABx',
    name: '120/ABx (Náhradní kyvadlová - pouze víkendy)',
    stops: [
      { id: '120abx_1', name: 'Horní Slavkov Kounice', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120abx_2', name: 'Horní Slavkov u kostela', zone: 1, kmFromStart: 3.5, minutesFromStart: 12 },
      { id: '120abx_3', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 5.0, minutesFromStart: 15 },
    ],
  },
  {
    id: '125A',
    number: '125/A',
    name: '125/A',
    stops: [
      { id: '125a_1', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '125a_2', name: 'Horní Slavkov Internát (Náhradní)', zone: 2, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '125a_3', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 2.0, minutesFromStart: 4 },
      { id: '125a_4', name: 'Horní Slavkov Točná u fary', zone: 2, kmFromStart: 3.0, minutesFromStart: 6 },
      { id: '125a_5', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '125a_6', name: 'Horní Slavkov Staré náměstí', zone: 1, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '125a_7', name: 'Horní Slavkov nádražní škola', zone: 1, kmFromStart: 7.5, minutesFromStart: 15 },
      { id: '125a_8', name: 'Horní Slavkov u Hřiště', zone: 1, kmFromStart: 9.0, minutesFromStart: 18, isOnDemand: true },
      { id: '125a_9', name: 'Horní Slavkov u křižovatky', zone: 1, kmFromStart: 11.0, minutesFromStart: 22 },
      { id: '125a_10', name: 'Horní Slavkov u přejezdu (Zkušební)', zone: 2, kmFromStart: 12.5, minutesFromStart: 25 },
      { id: '125a_11', name: 'Horní Slavkov u zahrádek', zone: 2, kmFromStart: 15.0, minutesFromStart: 30 },
      { id: '125a_12', name: 'Horní Slavkov Spartak', zone: 3, kmFromStart: 17.5, minutesFromStart: 35 },
      { id: '125a_13', name: 'Horní Slavkov Garáže', zone: 3, kmFromStart: 19.0, minutesFromStart: 38 },
      { id: '125a_14', name: 'Horní Slavkov Lesopark', zone: 3, kmFromStart: 21.5, minutesFromStart: 43 },
      { id: '125a_15', name: 'Horní Slavkov Sídliště', zone: 4, kmFromStart: 25.0, minutesFromStart: 50 },
      { id: '125a_16', name: 'Horní Slavkov Náměstí', zone: 4, kmFromStart: 27.5, minutesFromStart: 55 },
    ],
  }
];

export const TICKET_TYPES: TicketType[] = [
  // --- ZÁKLADNÍ JÍZDNÉ (STANDARDNÍ) ---
  { id: 'adult', name: 'Dospělý (Základní)', multiplier: 1.0, category: 'basic', badge: '100%', description: 'Plné obyčejné jízdné pro cestující 18–65 let' },
  { id: 'child', name: 'Dítě (6–15 let)', multiplier: 0.5, category: 'basic', badge: '50%', description: 'Zlevněné jízdné pro děti od 6 do dovršení 15 let' },
  { id: 'student', name: 'Student (15–26 let)', multiplier: 0.5, category: 'basic', badge: '50%', description: 'Zlevněné jízdné pro žáky a studenty s průkazem ISIC/žákovským' },
  { id: 'senior', name: 'Senior (65+)', multiplier: 0.5, category: 'basic', badge: '50%', description: 'Zlevněné jízdné pro seniory od 65 do dovršení 70 let' },
  { id: 'senior70', name: 'Senior nad 70 let', multiplier: 0.25, category: 'basic', badge: '25%', description: 'Mimořádné zlevněné jízdné pro seniory od 70 let' },
  { id: 'senior_free', name: 'Senior 75+ (Bezplatná)', multiplier: 0, category: 'basic', badge: 'ZDARMA', description: 'Bezplatná přeprava pro seniory starší 75 let s čipovou kartou' },
  { id: 'junior', name: 'Dítě do 6 let', multiplier: 0, category: 'basic', badge: 'ZDARMA', description: 'Bezplatná přeprava dětí do dovršení 6 let v doprovodu' },
  { id: 'ztp', name: 'ZTP (Zvláštní)', multiplier: 0.25, category: 'basic', badge: '25%', description: 'Zlevněné jízdné pro držitele průkazu ZTP' },
  { id: 'ztpp', name: 'ZTP/P (Těžké postižení)', multiplier: 0.25, category: 'basic', badge: '25%', description: 'Zlevněné jízdné pro držitele průkazu ZTP/P' },
  { id: 'guide', name: 'Průvodce ZTP/P', multiplier: 0, category: 'basic', badge: 'ZDARMA', description: 'Bezplatná přeprava průvodce nebo vodicího psa držitele ZTP/P' },
  { id: 'blood', name: 'Dárce krve (Janský)', multiplier: 0.25, category: 'basic', badge: '25%', description: 'Zvýhodněné jízdné pro bezpříspěvkové dárce krve' },
  { id: 'veteran', name: 'Válečný veterán', multiplier: 0.25, category: 'basic', badge: '25%', description: 'Zvýhodněné jízdné pro válečné veterány s osvědčením' },
  { id: 'police', name: 'Policie / IZS ve službě', multiplier: 0, category: 'basic', badge: 'ZDARMA', description: 'Bezplatná přeprava příslušníků IZS ve stejnokroji' },
  { id: 'return_ticket', name: 'Zpáteční jízdenka (1 den)', multiplier: 1.8, category: 'basic', badge: 'ZPÁTEČNÍ', description: 'Zvýhodněná jízdenka na cestu tam a zpět v týž den' },
  { id: 'cross_county', name: 'Mezikrajská jízdenka', multiplier: 1.6, category: 'basic', badge: 'MEZIKRAJ', description: 'Jízdné s přeshraničním přesahem do sousedního okresu/kraje' },

  // --- ČASOVÉ A SÍŤOVÉ JÍZDENKY ---
  { id: 'transfer_30', name: 'Přestupní 30 minut', multiplier: 1.1, category: 'time', badge: '30m', description: 'Časová jízdenka s platností 30 minut a možností přestupu' },
  { id: 'transfer_30_disc', name: 'Přestupní 30 min (Zlevněná)', multiplier: 0.55, category: 'time', badge: '30m ZLEV.', description: 'Zlevněná přestupní 30 minut pro děti, žáky a seniory' },
  { id: 'transfer', name: 'Přestupní 60 minut', multiplier: 1.2, category: 'time', badge: '60m', description: 'Standardní přestupní jízdenka s platností 60 minut' },
  { id: 'transfer_disc', name: 'Přestupní 60 min (Zlevněná)', multiplier: 0.6, category: 'time', badge: '60m ZLEV.', description: 'Zlevněná přestupní 60 minut pro studenty a seniory' },
  { id: 'transfer_90', name: 'Přestupní 90 minut', multiplier: 1.5, category: 'time', badge: '90m', description: 'Rozšířená časová jízdenka s platností 90 minut' },
  { id: 'transfer_90_disc', name: 'Přestupní 90 min (Zlevněná)', multiplier: 0.75, category: 'time', badge: '90m ZLEV.', description: 'Zlevněná přestupní 90 minut pro studenty a seniory' },
  { id: 'day', name: 'Celodenní 24 hodin', multiplier: 4.0, category: 'time', badge: '24h', description: 'Neomezené cestování po celé síti po dobu 24 hodin' },
  { id: 'day_discount', name: 'Celodenní 24h (Zlevněná)', multiplier: 2.0, category: 'time', badge: '24h ZLEV.', description: 'Zlevněná celodenní jízdenka pro žáky, studenty a důchodce' },
  { id: 'weekend48', name: 'Víkendová 48 hodin', multiplier: 6.5, category: 'time', badge: '48h', description: 'Dvoudenní neomezená síťová jízdenka na sobotu a neděli' },
  { id: 'weekend48_disc', name: 'Víkendová 48h (Zlevněná)', multiplier: 3.25, category: 'time', badge: '48h ZLEV.', description: 'Zlevněná víkendová jízdenka pro studenty a děti' },
  { id: 'tourist72', name: 'Turistická 3 dny (72h)', multiplier: 8.5, category: 'time', badge: '72h', description: 'Třídenní síťová jízdenka pro návštěvníky regionu' },
  { id: 'tourist5day', name: 'Lázeňská turistická 5 dní', multiplier: 12.0, category: 'time', badge: '5 DNÍ', description: 'Pětidenní turistická karta pro lázeňský trojúhelník a Slavkovsko' },
  { id: 'weekly7', name: 'Týdenní (7denní)', multiplier: 16.0, category: 'time', badge: '7 dní', description: '7denní nepřenosná časová jízdenka na vybranou relaci' },
  { id: 'region_net', name: 'Síťová celokrajská 24h', multiplier: 5.0, category: 'time', badge: 'KRAJ', description: 'Celokrajská integrovaná jízdenka na všechny linky IDS' },
  { id: 'region_net_disc', name: 'Síťová krajská 24h (Zlevněná)', multiplier: 2.5, category: 'time', badge: 'KRAJ ZLEV.', description: 'Zlevněná celokrajská jízdenka pro studenty a seniory' },
  { id: 'idok_1day', name: 'IDOK 1denní jízdenka', multiplier: 4.2, category: 'time', badge: 'IDOK', description: 'Platná na všechny vlaky a autobusy IDOK v Karlovarském kraji' },
  { id: 'night', name: 'Noční jízdenka', multiplier: 1.3, category: 'time', badge: 'NOC', description: 'Jízdenka pro spoje provozované v době od 23:00 do 04:30' },
  { id: 'night_disc', name: 'Noční zlevněná', multiplier: 0.65, category: 'time', badge: 'NOC ZLEV.', description: 'Zlevněné noční jízdné pro studenty a mládež' },

  // --- SKUPINOVÉ A RODINNÉ ---
  { id: 'family', name: 'Rodinná (2 dosp. + 3 děti)', multiplier: 2.5, category: 'group', badge: 'RODINA', description: 'Společná jízdenka pro 1 až 2 dospělé a až 3 děti do 15 let' },
  { id: 'family_weekend', name: 'Rodinná Víkendová 24h', multiplier: 3.5, category: 'group', badge: 'VÍKEND', description: 'Celodenní rodinná síťová jízdenka platná o víkendu' },
  { id: 'family_idok', name: 'Rodinná celokrajská IDOK', multiplier: 4.8, category: 'group', badge: 'RODINA KRAJ', description: 'Celodenní rodinná jízdenka pro celý Karlovarský kraj' },
  { id: 'duo', name: 'Dvojice (2 dospělí)', multiplier: 1.9, category: 'group', badge: '2 OS', description: 'Zvýhodněné společné jízdné pro 2 dospělé cestující' },
  { id: 'group_small', name: 'Skupinová (do 5 osob)', multiplier: 3.8, category: 'group', badge: '5 OS', description: 'Skupinová jízdenka pro libovolnou skupinu až 5 cestujících' },
  { id: 'group_medium', name: 'Skupinová (do 10 osob)', multiplier: 6.5, category: 'group', badge: '10 OS', description: 'Hromadná jízdenka pro zájmové skupiny a turistické oddíly' },
  { id: 'school_group', name: 'Školní (10 žáků + 1 dopr.)', multiplier: 5.0, category: 'group', badge: 'ŠKOLA', description: 'Hromadné jízdné pro školní výpravy do 11 osob celkem' },
  { id: 'school_group_large', name: 'Školní třída (25 žáků + 3 dopr.)', multiplier: 10.0, category: 'group', badge: 'TŘÍDA (28)', description: 'Výhodné hromadné jízdné pro celou školní třídu' },
  { id: 'group_large', name: 'Skupinová velká (do 20 os.)', multiplier: 9.0, category: 'group', badge: '20 OS', description: 'Hromadné jízdné pro organizované zájezdy a spolky' },

  // --- ZAVAZADLA, ZVÍŘATA A JÍZDNÍ KOLA ---
  { id: 'luggage', name: 'Pes / Zavazadlo', multiplier: 0.3, category: 'luggage', badge: 'ZAVAZADLO', description: 'Přepravné za psa bez schrány nebo zavazadlo nad 20x30x50 cm' },
  { id: 'dog_muzzle', name: 'Pes s náhubkem', multiplier: 0.3, category: 'luggage', badge: 'PES', description: 'Přepravné za psa drženého na vodítku s náhubkem' },
  { id: 'dog_day', name: 'Pes - celodenní přepravné', multiplier: 0.8, category: 'luggage', badge: 'PES 24H', description: 'Celodenní síťový lístek pro psa platný 24 hodin' },
  { id: 'bike', name: 'Jízdní kolo', multiplier: 0.6, category: 'luggage', badge: 'KOLO', description: 'Přeprava jednoho standardního jízdního kola' },
  { id: 'bike_day', name: 'Jízdní kolo - celodenní', multiplier: 1.4, category: 'luggage', badge: 'KOLO 24H', description: 'Celodenní přepravné pro jízdní kolo na všech linkách' },
  { id: 'bike_tourist', name: 'Cykloturistická 24h (Osoba+Kolo)', multiplier: 4.8, category: 'luggage', badge: 'CYKLO 24H', description: 'Kombinovaná celodenní síťová jízdenka pro cyklistu i jeho kolo' },
  { id: 'ebike_scooter', name: 'Elektrokoloběžka / E-kolo', multiplier: 0.7, category: 'luggage', badge: 'E-BIKE', description: 'Přeprava elektrokola nebo skládací elektrokoloběžky' },
  { id: 'oversize', name: 'Nadrozměrné zavazadlo', multiplier: 0.8, category: 'luggage', badge: 'MAX', description: 'Přepravné za velká břemena a objemná zavazadla' },
  { id: 'pram_child', name: 'Kočárek s dítětem', multiplier: 0, category: 'luggage', badge: 'ZDARMA', description: 'Bezplatná přeprava dětského kočárku s přepravovaným dítětem' },
  { id: 'pram_empty', name: 'Kočárek prázdný', multiplier: 0.4, category: 'luggage', badge: 'KOČÁREK', description: 'Přepravné za dětský kočárek bez přítomnosti dítěte' },
  { id: 'ski_snowboard', name: 'Lyže / Snowboard / Boby', multiplier: 0.3, category: 'luggage', badge: 'SPORT', description: 'Přepravné za 1 pár lyží v obalu, snowboard nebo sáňky/boby' },
  { id: 'pet_carrier', name: 'Zvíře v přepravce', multiplier: 0.25, category: 'luggage', badge: 'SCHRÁNA', description: 'Přepravné za drobná domácí zvířata v uzavřené schráně' },

  // --- DOPLŇKOVÉ A ZVLÁŠTNÍ ---
  { id: 'fine', name: 'Přirážka (bez jízdenky)', multiplier: 4.5, category: 'special', badge: 'POKUTA', description: 'Zákonná přirážka k jízdnému při nezakoupení jízdenky' },
  { id: 'pollution_fine', name: 'Znečištění vozu (přirážka)', multiplier: 5.5, category: 'special', badge: 'ZNEČIŠTĚNÍ', description: 'Smluvní pokuta za znečištění nebo poškození interiéru vozu' },
  { id: 'delay', name: 'Zpožděnka (doklad)', multiplier: 0, category: 'special', badge: 'POTVRZENÍ', description: 'Úřední potvrzení o zpoždění spoje pro zaměstnavatele/školu' },
  { id: 'receipt', name: 'Potvrzení o jízdném', multiplier: 0, category: 'special', badge: 'DOKLAD', description: 'Daňový doklad a potvrzení o úhradě jízdného na vyžádání' },
  { id: 'reservation', name: 'Místenka k sezení', multiplier: 0.5, category: 'special', badge: 'MÍSTENKA', description: 'Garantovaná rezervace konkrétního místa k sezení' },
  { id: 'bike_reservation', name: 'Místenka pro jízdní kolo', multiplier: 0.4, category: 'special', badge: 'REZERVACE', description: 'Rezervace místa na cyklodržáku vozidla' },
  { id: 'admin_fee', name: 'Manipulační poplatek', multiplier: 0.5, category: 'special', badge: 'SERVIS', description: 'Servisní poplatek za doplňkové odbavovací služby' },
  { id: 'chip_topup_100', name: 'Dobití čipové karty 100 Kč', multiplier: 6.67, category: 'special', badge: 'KREDIT 100', description: 'Kreditní dobití dopravní čipové karty DPHS / IDOK' },
  { id: 'chip_topup_200', name: 'Dobití čipové karty 200 Kč', multiplier: 13.33, category: 'special', badge: 'KREDIT 200', description: 'Kreditní dobití dopravní čipové karty DPHS / IDOK' },
];

export const DRIVERS: Driver[] = [
  { id: 'd4', name: 'Štěpán Stredni', pin: '260308' },
  { id: 'd1', name: 'Jan Novák', pin: '1234' },
  { id: 'd2', name: 'Petr Svoboda', pin: '0000' },
  { id: 'd3', name: 'Admin (DPHS)', pin: '9999' },
];

export const BASE_PRICE = 15;
export const PRICE_PER_ZONE = 8;

export const SERVICE_ANNOUNCEMENTS = [
  { id: 'a1', label: "Nenastupujte", category: "provoz", text: "Prosíme nenastupujte, vozidlo je mimo provoz." },
  { id: 'a2', label: "Změna trasy (Odklon)", category: "vyluka", text: "Pozor, z důvodu výluky jede vozidlo po odklonové trase." },
  { id: 'a3', label: "Konečná zastávka", category: "provoz", text: "Vážení cestující, tato zastávka je konečná. Prosíme vystupte." },
  { id: 'a4', label: "Přepravní kontrola", category: "jizdenky", text: "Vážení cestující, připravte si prosím své jízdní doklady ke kontrole přepravním kontrolorem." },
  { id: 'a5', label: "Zpoždění spoje", category: "provoz", text: "Vážení cestující, omlouváme se za zpoždění spoje z provozních důvodů." },
  { id: 'a6', label: "Čekání na přípoj", category: "provoz", text: "Vozidlo čeká na přípoj od jiného spoje. Prosíme o strpení." },
  { id: 'a7', label: "Zákaz jídla a pití", category: "bezpecnost", text: "Upozorňujeme cestující, že ve vozidle platí zákaz konzumace potravin a nápojů." },
  { id: 'a8', label: "Nástup s kočárky", category: "bezpecnost", text: "Prosíme cestující s kočárky, aby nastupovali a vystupovali určenými středními dveřmi." },
  { id: 'a9', label: "Roušky a hygiena", category: "bezpecnost", text: "Doporučujeme cestujícím používat ve vozidle ochranu dýchacích cest při respiračních obtížích." },
  { id: 'a10', label: "Klimatizace v chodu", category: "pohodli", text: "Vozidlo je vybaveno automatickou klimatizací. Prosíme, neotevírejte větrací okna." },
  { id: 'a11', label: "Nástup předními dveřmi", category: "jizdenky", text: "Vážení cestující, nastupujte prosím pouze předními dveřmi a připravte si jízdní doklady k nahlédnutí." },
  { id: 'a12', label: "Přísný zákaz kouření", category: "bezpecnost", text: "Upozorňujeme cestující, že ve všech prostorách vozidla platí přísný zákaz kouření, a to včetně elektronických cigaret a zahřívaného tabáku." },
  { id: 'a13', label: "Uvolněte místa k sezení", category: "pohodli", text: "Prosíme cestující, aby uvolnili místa k sezení osobám se sníženou pohyblivostí, těhotným ženám a starším spoluobčanům." },
  { id: 'a14', label: "Pozor na kapsáře", category: "bezpecnost", text: "Vážení cestující, věnujte zvýšenou pozornost svým osobním věcem a příručním zavazadlům. Pozor na kapsáře." },
  { id: 'a15', label: "Poděkování dopravce", category: "pohodli", text: "Děkujeme, že využíváte služeb naší dopravní společnosti a přejeme vám příjemnou a bezpečnou cestu." },
  { id: 'a16', label: "Příští zastávka", category: "provoz", text: "Příští zastávka: " },
  { id: 'a17', label: "Aktuální zastávka", category: "provoz", text: "Tato zastávka je: " },
  { id: 'a18', label: "Změna tarifu", category: "jizdenky", text: "Upozorňujeme cestující na změnu tarifu od prvního příštího měsíce. Více informací naleznete na vývěskách a webu dopravce." },
  { id: 'a19', label: "Ztráty a nálezy", category: "pohodli", text: "V případě nálezu zapomenutých věcí je prosím bezodkladně odevzdejte řidiči vozidla. Děkujeme." },
  { id: 'a20', label: "Technická závada", category: "provoz", text: "Omlouváme se, vozidlo má technickou závadu a nemůže pokračovat v jízdě. Vyčkejte prosím na náhradní spoj." },
  { id: 'a21', label: "Bezplatné Wi-Fi připojení", category: "pohodli", text: "V tomto vozidle je k dispozici bezplatné Wi-Fi připojení k internetu. Název sítě: Bus-Free-WiFi." },
  { id: 'a22', label: "Zpráva o výluce (Oprava linek)", category: "vyluka", text: "Vážení cestující, od 1. září 2026 jezdí linky 120/A, 120/B, 120/C1, 120/C2 a linka 219 pouze v pracovních dnech. O víkendech je provoz těchto linek z důvodu uzavírky Kostelní ulice zrušen. Jako náhradní dopravu o víkendech využijte výhradně kyvadlovou linku 120/ABx nebo víkendovou linku přes Haldu. Děkujeme za pochopení." },
  { id: 'a23', label: "Kyvadlová doprava 120/ABx (Pouze víkendy)", category: "vyluka", text: "Vážení cestující, linka 120/ABx je vedena jako náhradní kyvadlová doprava mezi zastávkami Horní Slavkov staré náměstí a Horní Slavkov Kounice. Od 1. září 2026 je v provozu výhradně o víkendech až do 1. prosince 2026, neboť v pracovních dnech jezdí běžné linky 120 po své standardní trase. Děkujeme za pochopení." },
  { id: 'a24', label: "Linka 219 (Trasa a omezení)", category: "vyluka", text: "Vážení cestující, linka 219 jede v trase Horní Slavkov Sídliště, náměstí, u Nádražní školy, staré náměstí, u kostela, Točná v Kostelní ulici, u hřbitova, Kounice internát a Kounice konečná. Linka je v provozu pouze v pracovních dnech, o víkendech je kvůli uzavírce Kostelní ulice zrušena." },
  { id: 'a25', label: "Linka Halda (Pracovní dny)", category: "vyluka", text: "Vážení cestující, tento spoj linky přes Haldu jede v režimu pracovních dnů přes zastávky Sídliště, Halda u mostu, Halda na mostě, na Haldě, Kounice hřiště a Kounice konečná." },
  { id: 'a26', label: "Víkendová náhradní doprava (Info)", category: "vyluka", text: "Upozornění pro cestující: Linky 120/A, 120/B, 120/C1, 120/C2 a linka 219 o víkendech nejezdí kvůli uzavírce Kostelní ulice. Pro přepravu o víkendu využijte náhradní linky: kyvadlovou 120/ABx (Staré náměstí ↔ Kounice) nebo víkendovou linku přes Haldu." },
  
  // --- NOVÁ SLUŽEBNÍ HLÁŠENÍ ---
  { id: 'a27', label: "Přidržujte se za jízdy", category: "bezpecnost", text: "Vážení cestující, z důvodu bezpečnosti přepravy se za jízdy vždy pevně přidržujte přídržných tyčí a madel." },
  { id: 'a28', label: "Uvolněte prostor dveří", category: "bezpecnost", text: "Žádáme cestující, aby neblokovali prostor dveří a umožnili rychlý a plynulý nástup a výstup." },
  { id: 'a29', label: "Povinnost platného lístku", category: "jizdenky", text: "Upozorňujeme cestující na povinnost mít platný jízdní doklad bezprostředně po nástupu do vozidla." },
  { id: 'a30', label: "Zastávka na znamení (Upozornění)", category: "provoz", text: "Upozorňujeme, že následující zastávky jsou na znamení. Pro výstup stiskněte včas signalizační tlačítko STOP." },
  { id: 'a31', label: "Přednost vystupujícím", category: "pohodli", text: "Prosíme nastupující cestující, aby nejprve nechali vystoupit cestující z vozu a nezatarasovali nástupní prostor." },
  { id: 'a32', label: "Přeprava psů (Pravidla)", category: "bezpecnost", text: "Upozorňujeme cestující se psy, že pes smí být přepravován výhradně s nasazeným bezpečným náhubkem a na krátkém vodítku." },
  { id: 'a33', label: "Jízdní kola a koloběžky", category: "bezpecnost", text: "Přeprava jízdních kol a rozměrných koloběžek je povolena pouze na vyhrazené plošině a se souhlasem řidiče." },
  { id: 'a34', label: "Zákaz jízdy uvnitř vozu", category: "bezpecnost", text: "Upozorňujeme, že jízda na koloběžkách, skateboardech a kolečkových bruslích ve vozidle je z bezpečnostních důvodů přísně zakázána." },
  { id: 'a35', label: "Podezřelá a opuštěná zavazadla", category: "bezpecnost", text: "Vážení cestující, v případě nálezu opuštěných či podezřelých předmětů a zavazadel ihned informujte řidiče vozidla." },
  { id: 'a36', label: "Bezpečnostní přestávka / Střídání", category: "provoz", text: "Vážení cestující, v této zastávce probíhá bezpečnostní přestávka a střídání řidičů. Zdržení spoje bude přibližně tři minuty." },
  { id: 'a37', label: "Dopravní kolona a zdržení", category: "provoz", text: "Vážení cestující, omlouváme se za vzniklé zpoždění způsobené hustým provozem a dopravními kolonami na trase." },
  { id: 'a38', label: "Zhoršené počasí a náledí", category: "provoz", text: "Z důvodu námrazy a zhoršené sjízdnosti vozovky jede vozidlo se zvýšenou opatrností. Děkujeme za pochopení." },
  { id: 'a39', label: "Přestup na vlakové spoje", category: "provoz", text: "Vážení cestující, v následující zastávce Nádraží je možný přestup na osobní a spěšné vlaky Českých drah." },
  { id: 'a40', label: "Náhradní autobusová doprava (NAD)", category: "vyluka", text: "Tento spoj jede jako náhradní autobusová doprava za vyloučený úsek železniční tratě. Jízdní doklady železnice platí." },
  { id: 'a41', label: "Školní posilový spoj", category: "provoz", text: "Upozorňujeme cestující, že tento spoj je veden přednostně pro přepravu žáků a studentů do školských zařízení." },
  { id: 'a42', label: "Zákaz stání u řidiče", category: "bezpecnost", text: "Žádáme cestující, aby nestáli ve vyznačeném žlutém prostoru u kabiny řidiče a nebránili ve výhledu do pravého zrcátka." },
  { id: 'a43', label: "Noční klid a ohleduplnost", category: "pohodli", text: "Žádáme cestující, aby zachovávali noční klid, nerušili ostatní hlasitou reprodukcí a chovali se ohleduplně." },
  { id: 'a44', label: "Bezkontaktní platba kartou", category: "jizdenky", text: "Vážení cestující, jízdenky u řidiče můžete uhradit pohodlně a bezhotovostně bezkontaktní platební kartou, mobilem nebo hodinkami." },
  { id: 'a45', label: "Uvolněte plošinu pro kočárek/vozík", category: "pohodli", text: "Upozorňujeme cestující na sklopných sedadlech, že v případě nástupu vozíčkáře nebo kočárku je nutné tato sedadla neprodleně uvolnit." },
  { id: 'a46', label: "Zákaz rušení řidiče za jízdy", category: "bezpecnost", text: "Upozorňujeme cestující, že za jízdy je přísně zakázáno mluvit na řidiče a jakkoliv odvádět jeho pozornost od řízení." },
  { id: 'a47', label: "Mimořádný odklon (Nehoda)", category: "vyluka", text: "Upozorňujeme cestující, že z důvodu dopravní nehody na původní trase jede tento spoj po mimořádné objízdné trase." },
  { id: 'a48', label: "Poslední spoj linky", category: "provoz", text: "Upozorňujeme, že se jedná o poslední spoj dne na této lince. Děkujeme, že cestujete s námi, a přejeme dobrou noc." },
  { id: 'a49', label: "Zákaz vstupu s jízdním kolem při plném voze", category: "bezpecnost", text: "Z důvodu plné kapacity vozidla nelze na tomto spoji přepravit další jízdní kola a nadrozměrná břemena." },
  { id: 'a50', label: "Kontrola jízdenek při nástupu", category: "jizdenky", text: "Vážení cestující, v tomto úseku platí povinnost prokázat se platným jízdním dokladem při nástupu do vozidla." },
  { id: 'a51', label: "Stavební práce Slavkov – Loket", category: "vyluka", text: "Pozor, v úseku Horní Slavkov až Loket probíhají plánované práce na silnici. Očekávejte mírné zpoždění." },
  { id: 'a52', label: "Očištění obuvi v zimě", category: "bezpecnost", text: "Žádáme cestující, aby si v zimním období před nástupem do vozu očistili obuv od sněhu a ledu a předešli uklouznutí." },
  { id: 'a53', label: "Výluka železnice Vary – Sokolov", category: "vyluka", text: "Upozorňujeme na probíhající výluku železniční tratě mezi stanicemi Karlovy Vary a Sokolov. Využijte náhradní spoje." },
  { id: 'a54', label: "Přestup směr Bečov a M. Lázně", category: "provoz", text: "V následující přestupní zastávce je zajištěn návazný spoj příměstských linek směr Bečov nad Teplou a Mariánské Lázně." },
  { id: 'a55', label: "Zapomenuté mobily a deštníky", category: "pohodli", text: "Vážení cestující, zkontrolujte si prosím své osobní věci před výstupem z vozidla. Dbejte na mobily, klíče a deštníky." },
  { id: 'a56', label: "Ohleduplné telefonování", category: "pohodli", text: "Žádáme cestující, aby při telefonování ve vozidle používali sluchátka nebo mluvili ohleduplně a nerušili spolucestující." },
  { id: 'a57', label: "Připravte si přesné drobné či kartu", category: "jizdenky", text: "Pro zrychlení odbavení u řidiče mějte prosím připravenou přesnou částku v hotovosti nebo bezkontaktní platební kartu." },
  { id: 'a58', label: "Přemístění zastávky Náměstí (+50m)", category: "vyluka", text: "Z důvodu stavebních úprav je zastávka Horní Slavkov náměstí dočasně posunuta o 50 metrů ve směru jízdy." },
  { id: 'a59', label: "Tarif IDOK v celém voze", category: "jizdenky", text: "Vážení cestující, na této lince plně platí přepravní a tarifní podmínky Integrované dopravy Karlovarského kraje IDOK." },
  { id: 'a60', label: "Nízkopodlažní vůz s plošinou", category: "pohodli", text: "Tento autobus je nízkopodlažní a disponuje mechanickou plošinou pro bezbariérový nástup kočárků a vozíčkářů." },
  { id: 'a61', label: "Vyhrazená sedadla vpředu", category: "pohodli", text: "Upozorňujeme, že první řady sedadel jsou přednostně vyhrazeny pro těhotné ženy, seniory a osoby s omezenou pohyblivostí." },
  { id: 'a62', label: "Znamení k výstupu včas", category: "provoz", text: "Na zastávkách na znamení stiskněte tlačítko STOP s dostatečným předstihem ještě před začátkem brzdění." },
  { id: 'a63', label: "Přípojný vlak má zpoždění", category: "provoz", text: "Vážení cestující, čekáme na zpožděný přípojný vlak. Předpokládaný odjezd za 4 minuty. Děkujeme za pochopení." },
  { id: 'a64', label: "Konec přepravní špičky", category: "provoz", text: "Dopravní špička skončila. Další spoje jedou podle pravidelného večerního intervalového jízdního řádu." },
];

export const SYSTEM_ERRORS = [
  "CHYBA TISKÁRNY - DOŠEL PAPÍR",
  "CHYBA GPS - SIGNÁL ZTRACEN",
  "MODUL PLATBY NEODPOVÍDÁ",
  "PŘEHŘÁTÍ SYSTÉMU",
  "CHYBA KOMUNIKACE S MODEMEM",
  "NÍZKÝ TLAK VZDUCHU - OKRUH 2",
  "PORUCHA MOTORU - OMEZENÝ VÝKON",
  "CHYBA ABS/ASR - NAVŠTIVTE SERVIS",
  "NÍZKÁ HLADINA CHLADICÍ KAPALINY",
  "PORUCHA PŘEVODOVKY - RETARDÉR KO",
  "CHYBA OSVĚTLENÍ - VNĚJŠÍ OKRUH",
  "PORUCHA PALUBNÍHO POČÍTAČE - RESTART",
  "CHYBA ČTEČKY KARET - RESTARTUJTE",
  "NÍZKÝ TLAK V PNEUMATIKÁCH",
  "PŘETÍŽENÍ ELEKTRICKÉ SÍTĚ",
];

export const DISPATCHER_MESSAGES = [
  "DISPEČINK: Linky 120/A, 120/B, 120/C1, 120/C2 a linka 219 jezdí pouze v prac. dnech. O víkendech je Kostelní ulice uzavřena a linky nejezdí! Náhrada: 120/ABx a 120/Halda.",
  "DISPEČINK: Náhradní kyvadlová linka 120/ABx je provozována výhradně o víkendech!",
  "LINKA 219: Linka 219 (Sídliště – Kounice) jezdí pouze v pracovních dnech. Pozor na čekání 12-14 min na Starém náměstí.",
  "LINKA HALDA: V pracovních dnech platí zkrácená trasa Sídliště – Halda most – Halda na mostě – Kounice hřiště – Kounice.",
  "Pozor na náledí v úseku Horní Slavkov - Kounice.",
  "Zpoždění na lince 125 z důvodu nehody v centru.",
  "Všechny vozy: Přepněte na kanál 4.",
  "Kontrola jízdních dokladů nahlášena na zastávce Kounice.",
  "Zvýšený výskyt cestujících u nádraží, jeďte opatrně.",
  "Technická závada na trati, očekávejte pokyny.",
  "Dobrou chuť k obědu všem řidičům na trati!",
  "Hlášena ztráta peněženky v lince 120, prověřte vůz na konečné.",
  "Vyjíždí posilový spoj na linku 120/A.",
  "Pozor na silný vítr v otevřených úsecích.",
  "Všechny spoje linky 125 jedou s 5 minutovým zpožděním.",
  "Výměna vozu 4321 na lince 120/B za 10 minut na terminálu.",
  "Dispatcher: Registrujeme výpadek online sledování, hlášení zastávek provádějte manuálně.",
];

export const PASSENGER_FEEDBACK = [
  "Dobrý den, mohl byste prosím pustit trochu víc topení? Je tu zima.",
  "Děkuji za ochotu s kočárkem!",
  "Proč jedeme tak pomalu? Budu mít zpoždění do práce.",
  "Pustil byste prosím rádio? Tady je hrozné ticho.",
  "Mohl byste zavřít to okýnko u řidiče? Táhne na mě.",
  "Pěkný den přeji, pane řidiči!",
  "Máte tu hrozný vydýchaný vzduch, pusťte klimu.",
  "Můžu si u vás koupit jízdenku kartou?",
];
