import { Route, TicketType, Driver } from './types';

export const ROUTES: Route[] = [
  {
    id: '120A_REG',
    number: '120/A',
    name: '120/A (Běžná)',
    stops: [
      { id: '120a_reg_1', name: 'Horní Slavkov staré nám.', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120a_reg_2', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 1.5, minutesFromStart: 3 },
      { id: '120a_reg_3', name: 'Horní Slavkov v zatáčce', zone: 1, kmFromStart: 2.5, minutesFromStart: 5, isOnDemand: true },
      { id: '120a_reg_4', name: 'Horní Slavkov Točná u fary', zone: 2, kmFromStart: 3.5, minutesFromStart: 7 },
      { id: '120a_reg_5', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120a_reg_6', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '120a_reg_7', name: 'Horní Slavkov Kounice', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
    ],
  },
  {
    id: '120A_VYL',
    number: '120/A',
    name: '120/A (Výluka)',
    stops: [
      { id: '120a_vyl_1', name: 'Horní Slavkov Staré nám.', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120a_vyl_2', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 1.5, minutesFromStart: 3 },
      { id: '120a_vyl_3', name: 'Horní Slavkov v zatáčce', zone: 1, kmFromStart: 2.5, minutesFromStart: 5, isOnDemand: true },
      { id: '120a_vyl_4', name: 'Horní Slavkov Točná u fary', zone: 2, kmFromStart: 3.5, minutesFromStart: 7 },
      { id: '120a_vyl_5', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120a_vyl_6', name: 'Horní Slavkov u přejezdu', zone: 2, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '120a_vyl_7', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
      { id: '120a_vyl_8', name: 'Horní Slavkov u Hřiště Kounice', zone: 2, kmFromStart: 8.5, minutesFromStart: 17 },
    ],
  },
  {
    id: '120B_REG',
    number: '120/B',
    name: '120/B (Běžná)',
    stops: [
      { id: '120b_reg_1', name: 'Horní Slavkov staré nám.', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120b_reg_2', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120b_reg_3', name: 'Horní Slavkov Točná v Kostelní ul.', zone: 1, kmFromStart: 2.5, minutesFromStart: 5 },
      { id: '120b_reg_4', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 4.0, minutesFromStart: 8 },
      { id: '120b_reg_5', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 5.5, minutesFromStart: 11 },
      { id: '120b_reg_6', name: 'Horní Slavkov Kounice', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
    ],
  },
  {
    id: '120B_VYL',
    number: '120/B',
    name: '120/B (Výluka)',
    stops: [
      { id: '120b_vyl_1', name: 'Horní Slavkov Staré nám.', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120b_vyl_2', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120b_vyl_3', name: 'Horní Slavkov Točná v kostelní ul.', zone: 1, kmFromStart: 2.5, minutesFromStart: 5 },
      { id: '120b_vyl_4', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 4.0, minutesFromStart: 8 },
      { id: '120b_vyl_5', name: 'Horní Slavkov u přejezdu', zone: 2, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120b_vyl_6', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 6.5, minutesFromStart: 13 },
      { id: '120b_vyl_7', name: 'Horní Slavkov u Hřiště', zone: 2, kmFromStart: 7.5, minutesFromStart: 15 },
    ],
  },
  {
    id: '120C1_REG',
    number: '120/C1',
    name: '120/C1 (Běžná)',
    stops: [
      { id: '120c1_1', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120c1_2', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120c1_3', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 2.0, minutesFromStart: 4 },
      { id: '120c1_4', name: 'Horní Slavkov Točná ve Faře', zone: 2, kmFromStart: 3.0, minutesFromStart: 6 },
      { id: '120c1_5', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120c1_6', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '120c1_7', name: 'Horní Slavkov Nádražní škola', zone: 1, kmFromStart: 7.5, minutesFromStart: 15 },
      { id: '120c1_8', name: 'Horní Slavkov u šk. hřiště', zone: 1, kmFromStart: 9.0, minutesFromStart: 18, isOnDemand: true },
      { id: '120c1_9', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 11.0, minutesFromStart: 22 },
      { id: '120c1_10', name: 'Horní Slavkov náměstí', zone: 1, kmFromStart: 12.0, minutesFromStart: 24 },
      { id: '120c1_11', name: 'Horní Slavkov sídliště', zone: 1, kmFromStart: 15.0, minutesFromStart: 30 },
    ],
  },
  {
    id: '120C1_VYL',
    number: '120/C1',
    name: '120/C1 (Výluka)',
    stops: [
      { id: '120c1_vyl_1', name: 'Horní Slavkov sídliště', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120c1_vyl_2', name: 'Horní Slavkov náměstí', zone: 1, kmFromStart: 1.5, minutesFromStart: 7 },
      { id: '120c1_vyl_3', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 2.2, minutesFromStart: 10 },
      { id: '120c1_vyl_4', name: 'HS u Garáží (nad škol. hřištěm)', zone: 1, kmFromStart: 2.8, minutesFromStart: 13 },
      { id: '120c1_vyl_5', name: 'Horní Slavkov na mostě', zone: 1, kmFromStart: 3.5, minutesFromStart: 16 },
      { id: '120c1_vyl_6', name: 'Horní Slavkov u nádraží', zone: 1, kmFromStart: 4.0, minutesFromStart: 18 },
      { id: '120c1_vyl_7', name: 'Horní Slavkov u mostu', zone: 1, kmFromStart: 4.4, minutesFromStart: 20 },
      { id: '120c1_vyl_8', name: 'Horní Slavkov Halda pod mostem', zone: 1, kmFromStart: 5.1, minutesFromStart: 23 },
      { id: '120c1_vyl_9', name: 'Horní Slavkov Halda u mostu', zone: 2, kmFromStart: 5.6, minutesFromStart: 25 },
      { id: '120c1_vyl_10', name: 'Horní Slavkov Halda za mostem', zone: 2, kmFromStart: 6.7, minutesFromStart: 30 },
      { id: '120c1_vyl_11', name: 'Horní Slavkov na Haldě', zone: 2, kmFromStart: 7.8, minutesFromStart: 35 },
      { id: '120c1_vyl_12', name: 'HS Kounice u hřiště', zone: 2, kmFromStart: 8.9, minutesFromStart: 40 },
      { id: '120c1_vyl_13', name: 'Horní Slavkov Kounice Kounice', zone: 2, kmFromStart: 10.0, minutesFromStart: 45 },
    ],
  },
  {
    id: '120C2_REG',
    number: '120/C2',
    name: '120/C2 (Běžná)',
    stops: [
      { id: '120c2_1', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120c2_2', name: 'Horní Slavkov Kounice internát', zone: 2, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '120c2_3', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 2.0, minutesFromStart: 4 },
      { id: '120c2_4', name: 'Horní Slavkov Točná ve Faře', zone: 2, kmFromStart: 3.0, minutesFromStart: 6 },
      { id: '120c2_5', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '120c2_6', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '120c2_7', name: 'Horní Slavkov Náměstí', zone: 1, kmFromStart: 9.0, minutesFromStart: 18 },
      { id: '120c2_8', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 10.0, minutesFromStart: 20 },
      { id: '120c2_9', name: 'Horní Slavkov Lesopark', zone: 1, kmFromStart: 12.5, minutesFromStart: 25 },
    ],
  },
  {
    id: '120C2_VYL',
    number: '120/C2',
    name: '120/C2 (Výluka)',
    stops: [
      { id: '120c2_vyl_1', name: 'Horní Slavkov sídliště', zone: 1, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120c2_vyl_2', name: 'Horní Slavkov náměstí', zone: 1, kmFromStart: 1.5, minutesFromStart: 7 },
      { id: '120c2_vyl_3', name: 'Horní Slavkov u školky', zone: 1, kmFromStart: 2.2, minutesFromStart: 10 },
      { id: '120c2_vyl_4', name: 'HS u Garáží (nad škol. hřištěm)', zone: 1, kmFromStart: 2.8, minutesFromStart: 13 },
      { id: '120c2_vyl_5', name: 'Horní Slavkov na mostě', zone: 1, kmFromStart: 3.5, minutesFromStart: 16 },
      { id: '120c2_vyl_6', name: 'Horní Slavkov u nádraží', zone: 1, kmFromStart: 4.0, minutesFromStart: 18 },
      { id: '120c2_vyl_7', name: 'Horní Slavkov u mostu', zone: 1, kmFromStart: 4.4, minutesFromStart: 20 },
      { id: '120c2_vyl_8', name: 'Horní Slavkov Halda pod mostem', zone: 1, kmFromStart: 5.1, minutesFromStart: 23 },
      { id: '120c2_vyl_9', name: 'Horní Slavkov Halda u mostu', zone: 2, kmFromStart: 5.6, minutesFromStart: 25 },
      { id: '120c2_vyl_10', name: 'Horní Slavkov Halda za mostem', zone: 2, kmFromStart: 6.7, minutesFromStart: 30 },
      { id: '120c2_vyl_11', name: 'Horní Slavkov na Haldě', zone: 2, kmFromStart: 7.8, minutesFromStart: 35 },
      { id: '120c2_vyl_12', name: 'HS Kounice u hřiště', zone: 2, kmFromStart: 8.9, minutesFromStart: 40 },
      { id: '120c2_vyl_13', name: 'Horní Slavkov Kounice Kounice', zone: 2, kmFromStart: 10.0, minutesFromStart: 45 },
    ],
  },
  {
    id: '120_ABX',
    number: '120/ABx',
    name: '120/ABx (Náhradní kyvadlová)',
    stops: [
      { id: '120abx_1', name: 'Horní Slavkov Kounice', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '120abx_2', name: 'Horní Slavkov u kostela', zone: 1, kmFromStart: 3.5, minutesFromStart: 12 },
      { id: '120abx_3', name: 'Horní Slavkov staré náměstí', zone: 1, kmFromStart: 5.0, minutesFromStart: 15 },
    ],
  },
  {
    id: '125A',
    number: '125/A',
    name: '125/A',
    stops: [
      { id: '125a_1', name: 'Horní Slavkov Kounice (Náhradní)', zone: 2, kmFromStart: 0, minutesFromStart: 0 },
      { id: '125a_2', name: 'Horní Slavkov Internát (Náhradní)', zone: 2, kmFromStart: 1.0, minutesFromStart: 2 },
      { id: '125a_3', name: 'Horní Slavkov u hřbitova', zone: 2, kmFromStart: 2.0, minutesFromStart: 4 },
      { id: '125a_4', name: 'Horní Slavkov Točná u fary', zone: 2, kmFromStart: 3.0, minutesFromStart: 6 },
      { id: '125a_5', name: 'Horní Slavkov Točná u kostela', zone: 1, kmFromStart: 5.0, minutesFromStart: 10 },
      { id: '125a_6', name: 'Horní Slavkov Staré náměstí', zone: 1, kmFromStart: 6.0, minutesFromStart: 12 },
      { id: '125a_7', name: 'Horní Slavkov nádražní škola', zone: 1, kmFromStart: 7.5, minutesFromStart: 15 },
      { id: '125a_8', name: 'Horní Slavkov u Hřiště', zone: 1, kmFromStart: 9.0, minutesFromStart: 18, isOnDemand: true },
      { id: '125a_9', name: 'Horní Slavkov u křižovatky', zone: 1, kmFromStart: 11.0, minutesFromStart: 22 },
      { id: '125a_10', name: 'Horní Slavkov u přejezdu (Zkušební)', zone: 2, kmFromStart: 12.5, minutesFromStart: 25 },
      { id: '125a_11', name: 'Horní Slavkov u zahrádek', zone: 2, kmFromStart: 15.0, minutesFromStart: 30 },
      { id: '125a_12', name: 'Horní Slavkov Spartak', zone: 3, kmFromStart: 17.5, minutesFromStart: 35 },
      { id: '125a_13', name: 'Horní Slavkov Garáže', zone: 3, kmFromStart: 19.0, minutesFromStart: 38 },
      { id: '125a_14', name: 'Horní Slavkov Lesopark', zone: 3, kmFromStart: 21.5, minutesFromStart: 43 },
      { id: '125a_15', name: 'Horní Slavkov Sídliště', zone: 4, kmFromStart: 25.0, minutesFromStart: 50 },
      { id: '125a_16', name: 'Horní Slavkov Náměstí', zone: 4, kmFromStart: 27.5, minutesFromStart: 55 },
    ],
  }
];

export const TICKET_TYPES: TicketType[] = [
  { id: 'adult', name: 'Dospělý', multiplier: 1.0 },
  { id: 'student', name: 'Student (18-26)', multiplier: 0.5 },
  { id: 'senior', name: 'Senior (65+)', multiplier: 0.5 },
  { id: 'child', name: 'Dítě (6-18)', multiplier: 0.5 },
  { id: 'ztp', name: 'ZTP / ZTP-P', multiplier: 0.25 },
  { id: 'luggage', name: 'Pes / Zavazadlo', multiplier: 0.3 },
  { id: 'transfer', name: 'Přestupní', multiplier: 1.2 },
  { id: 'day', name: 'Časová 24h', multiplier: 4.0 },
  { id: 'family', name: 'Rodinná', multiplier: 2.5 },
  { id: 'junior', name: 'Junior (<6)', multiplier: 0 },
  { id: 'bike', name: 'Kolo', multiplier: 0.6 },
  { id: 'delay', name: 'Zpožděnka', multiplier: 0 },
  { id: 'receipt', name: 'Potvrzení', multiplier: 0 },
  { id: 'oversize', name: 'Nadrozměr', multiplier: 0.8 },
  { id: 'fine', name: 'Přirážka', multiplier: 4.5 },
];

export const DRIVERS: Driver[] = [
  { id: 'd1', name: 'Jan Novák', pin: '1234' },
  { id: 'd2', name: 'Petr Svoboda', pin: '0000' },
  { id: 'd3', name: 'Admin', pin: '9999' },
];

export const BASE_PRICE = 15;
export const PRICE_PER_ZONE = 8;

export const SERVICE_ANNOUNCEMENTS = [
  { id: 'a1', label: "Nenastupujte", text: "Prosíme nenastupujte, vozidlo je mimo provoz." },
  { id: 'a2', label: "Změna trasy", text: "Pozor, z důvodu výluky jede vozidlo po odklonové trase." },
  { id: 'a3', label: "Konečná", text: "Vážení cestující, tato zastávka je konečná. Prosíme vystupte." },
  { id: 'a4', label: "Revize", text: "Vážení cestující, připravte si prosím své jízdní doklady ke kontrole." },
  { id: 'a5', label: "Zpoždění", text: "Vážení cestující, omlouváme se za zpoždění spoje z provozních důvodů." },
  { id: 'a6', label: "Čekání", text: "Vozidlo čeká na přípoj od jiného spoje. Prosíme o strpení." },
  { id: 'a7', label: "Zákaz jídla", text: "Upozorňujeme cestující, že ve vozidle platí zákaz konzumace potravin a nápojů." },
  { id: 'a8', label: "Kočárky", text: "Prosíme cestující s kočárky, aby nastupovali a vystupovali určenými dveřmi." },
  { id: 'a9', label: "Roušky", text: "Doporučujeme cestujícím používat ve vozidle ochranu dýchacích cest." },
  { id: 'a10', label: "Klimatizace", text: "Vozidlo je vybaveno automatickou klimatizací. Prosíme, neotevírejte okna." },
  { id: 'a11', label: "Nástup předem", text: "Vážení cestující, nastupujte prosím pouze předními dveřmi a připravte si jízdní doklady." },
  { id: 'a12', label: "Zákaz kouření", text: "Upozorňujeme cestující, že ve všech prostorách vozidla platí přísný zákaz kouření, a to i elektronických cigaret." },
  { id: 'a13', label: "Uvolněte místo", text: "Prosíme cestující, aby uvolnili místa k sezení osobám se sníženou pohyblivostí a starším spoluobčanům." },
  { id: 'a14', label: "Pozor na kapsáře", text: "Vážení cestující, věnujte zvýšenou pozornost svým osobním věcem. Pozor na kapsáře." },
  { id: 'a15', label: "Děkujeme", text: "Děkujeme, že využíváte služeb naší dopravní společnosti a přejeme vám příjemnou cestu." },
  { id: 'a16', label: "Příští zastávka", text: "Příští zastávka: " },
  { id: 'a17', label: "Aktuální zastávka", text: "Tato zastávka je: " },
  { id: 'a18', label: "Změna tarifu", text: "Upozorňujeme cestující na změnu tarifu od prvního příštího měsíce. Více informací na webu dopravce." },
  { id: 'a19', label: "Ztráty a nálezy", text: "V případě nálezu zapomenutých věcí je prosím odevzdejte řidiči vozidla. Děkujeme." },
  { id: 'a20', label: "Technická závada", text: "Omlouváme se, vozidlo má technickou závadu. Vyčkejte prosím na náhradní spoj." },
  { id: 'a21', label: "WiFi", text: "V tomto vozidle je k dispozici bezplatné WiFi připojení. Název sítě: Bus-Free-WiFi." },
  { id: 'a22', label: "Mimořádná Výluka", text: "Vážení cestující, od dvacátého července dva tisíce dvacet šest do prvního prosince dva tisíce dvacet šest platí mimořádná výluka na linkách sto dvacet lomeno cé jedna a sto dvacet lomeno cé dva. Z důvodu uzavírky Kostelní ulice a fary jedou spoje po odklonové trase přes zastávky: u Garáží, na mostě, u nádraží, u mostu, Halda pod mostem, Halda u mostu, Halda za mostem, na Haldě a Kounice u hřiště. Tyto linky zcela vynechávají zastávky: u školního hřiště, Nádražní škola, staré náměstí, Točná u kostela, Točná v Kostelní ulici, v zatáčce, Točná u fary, u Hřbitova a Kounice internát. Náhradní přepravu v neobsluhovaném úseku mezi zastávkami Horní Slavkov staré náměstí a Horní Slavkov Kounice zajišťuje kyvadlová linka sto dvacet lomeno á bé iks. Upozorňujeme také, že běžné linky sto dvacet lomeno á a sto dvacet lomeno bé jsou po dobu výluky v pracovních dnech zrušeny. Děkujeme za pochopení." },
];

export const SYSTEM_ERRORS = [
  "CHYBA TISKÁRNY - DOŠEL PAPÍR",
  "CHYBA GPS - SIGNÁL ZTRACEN",
  "MODUL PLATBY NEODPOVÍDÁ",
  "PŘEHŘÁTÍ SYSTÉMU",
  "CHYBA KOMUNIKACE S MODEMEM",
  "NÍZKÝ TLAK VZDUCHU - OKRUH 2",
  "PORUCHA MOTORU - OMEZENÝ VÝKON",
  "CHYBA ABS/ASR - NAVŠTIVTE SERVIS",
  "NÍZKÁ HLADINA CHLADICÍ KAPALINY",
  "PORUCHA PŘEVODOVKY - RETARDÉR KO",
  "CHYBA OSVĚTLENÍ - VNĚJŠÍ OKRUH",
  "PORUCHA PALUBNÍHO POČÍTAČE - RESTART",
  "CHYBA ČTEČKY KARET - RESTARTUJTE",
  "NÍZKÝ TLAK V PNEUMATIKÁCH",
  "PŘETÍŽENÍ ELEKTRICKÉ SÍTĚ",
];

export const DISPATCHER_MESSAGES = [
  "VÝLUKA: Od dnešního dne do 1.12.2026 platí velká výluka na linkách 120/C1 a 120/C2! Jízda odklonem přes Haldu a Kounice u hřiště.",
  "Pozor na náledí v úseku Horní Slavkov - Kounice.",
  "Zpoždění na lince 125 z důvodu nehody v centru.",
  "Všechny vozy: Přepněte na kanál 4.",
  "Kontrola jízdních dokladů nahlášena na zastávce Kounice.",
  "Zvýšený výskyt cestujících u nádraží, jeďte opatrně.",
  "Technická závada na trati, očekávejte pokyny.",
  "Dobrou chuť k obědu všem řidičům na trati!",
  "Hlášena ztráta peněženky v lince 120, prověřte vůz na konečné.",
  "Vyjíždí posilový spoj na linku 120/A.",
  "Pozor na silný vítr v otevřených úsecích.",
  "Všechny spoje linky 125 jedou s 5 minutovým zpožděním.",
  "Výměna vozu 4321 na lince 120/B za 10 minut na terminálu.",
  "Dispatcher: Registrujeme výpadek online sledování, hlášení zastávek provádějte manuálně.",
];

export const PASSENGER_FEEDBACK = [
  "Dobrý den, mohl byste prosím pustit trochu víc topení? Je tu zima.",
  "Děkuji za ochotu s kočárkem!",
  "Proč jedeme tak pomalu? Budu mít zpoždění do práce.",
  "Pustil byste prosím rádio? Tady je hrozné ticho.",
  "Mohl byste zavřít to okýnko u řidiče? Táhne na mě.",
  "Pěkný den přeji, pane řidiči!",
  "Máte tu hrozný vydýchaný vzduch, pusťte klimu.",
  "Můžu si u vás koupit jízdenku kartou?",
];
